spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: 140400
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8081

logging:
  level:
    org.springframework: INFO
    com.unisocial: DEBUG